const products = [
    {
        id: 1,
        name: "Running Shoes",
        image: "/src/assets/assets/images/Running-Shoes.webp",
        price: 1200,
        oldPrice: 1500,
        rating: 4,
        discount: 20,
        category: "Clothing",
    },
    {
        id: 2,
        name: "Smart Watch",
        image: "/src/assets/assets/images/smartwatch.jpg",
        price: 800,
        oldPrice: 1000,
        rating: 5,
        discount: 20,
        category: "Electronics",
    },
    {
        id: 3,
        name: "Wireless Earbuds",
        image: "/src/assets/assets/images/wirelessearbuds.jpg",
        price: 150,
        oldPrice: 200,
        rating: 4,
        discount: 25,
        category: "Electronics",
    },
    {
        id: 4,
        name: "Gaming Laptop",
        image: "/src/assets/assets/images/gaminglap.jpg",
        price: 18500,
        oldPrice: 20000,
        rating: 4,
        discount: 25,
        category: "Electronics",
    },
    {
        id: 5,
        name: "Laptop Bag",
        image: "/src/assets/assets/images/laptopbag.jpg",
        price: 500,
        oldPrice: 700,
        rating: 4,
        discount: 30,
        category: "Accessories",
    },
];

module.exports = products;